openapi: 3.1.0
info:
  title: GPT Domain Verifier
  version: 1.0.0
servers:
  - url: https://gpt-verifier.onrender.com
paths:
  /verify:
    get:
      operationId: verifyUser
      summary: Verifies the user's email is from @edu.jmc.ac.il
      responses:
        '200':
          description: Authorized
          content:
            application/json:
              schema:
                type: object
                properties:
                  email:
                    type: string
                  domainVerified:
                    type: boolean
        '401':
          description: Missing or invalid token
        '403':
          description: Unauthorized domain
